<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Icons\Home.png" />
    <None Remove="Icons\Home_mine.png" />
    <None Remove="Icons\Settings.jpg" />
    <None Remove="Icons\Settings.png" />
    <None Remove="Icons\Tasks.png" />
    <None Remove="Icons\Todo.png" />
    <None Remove="SaveDB.db" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="SaveDB.db">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="IX.Observable" Version="0.7.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="System.Data.SQLite" Version="1.0.117" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Icons\Home.png" />
    <Resource Include="Icons\Home_mine.png" />
    <Resource Include="Icons\AppIcon.png" />
    <Resource Include="Icons\Settings.jpg" />
    <Resource Include="Icons\Settings.png" />
    <Resource Include="Icons\Tasks.png" />
    <Resource Include="Icons\Todo.png" />
  </ItemGroup>

</Project>
